### ISSUE TITLE
Buying a PCB

### ISSUE THREAD

**Issue by DamienC666** [Marco-Both/M396F-Replika#1]
Sorry to contact you in this manner but I couldn't find an e-mail address or other means of communication.

I'm interested in purchasing a M396F Replica PCB. I got some quotes to have the PCB manufactured myself, but most online manufacturers want a minimum of 3-5 boards at several hundred dollars USD and I only need one.

If you have one available you'd be willing to sell, I am interested in buying, or if you could recommend an affordable manufacturer I would appreciate it.

Thanks

**Comment by Marco-Both** [comment]
Hello,

no problem. JLCPCB is quite inexpensive. I would also have a board here. You can get it. Feel free to write me an email at EDIT

**Comment by Marco-Both** [comment]
pcb shipped
