### ISSUE TITLE
Possible U6 replacement with a DIP-14 oscillator

### ISSUE THREAD

**Issue by skiselev** [Marco-Both/M396F-Replika#6]
It appears that it is possible to use a crystal oscillator in a DIP-14 package instead of U6 PLL.
It might be a more available option at this time.

Has this option been tested with the M396F-Replica?

Here is a [photo of a motherboard with a crystal oscillator](https://www.dosdays.co.uk/media/pcchips/M396F/M396F_v2.2.jpg).

**Comment by Marco-Both** [comment]
Rev 2.2 is an older version of the board. I can't say why they changed from crystal oscillator to DIP IC. Maybe cost reasons?

I need to check the PINOUT and maybe make a wire or two. Then a DIP14 should also work. The TK9107-2 or ICW42C07 are readily available from UTSource. 1-2 € per piece.

**Comment by skiselev** [comment]
I checked the layout. Either DIP-14 (aka "full can") or DIP-8 (aka "half can") oscillators should work.

The oscillator is installed instead of U6, JP9, and JP10.

For DIP-14 oscillator, pin 7 of the oscillator goes to the pin 1 of the JP9 (ground), pin 14 of the oscillator goes to pin 3 of JP10 (VCC), the oscillator output, pin 8, is connected to the hole on the right from JP9, and pin 1 of the oscillator goes to the hole on the left from JP10.

For DIP-8 oscillator, pin 4 of the oscillator goes to the pin 1 of the JP9 (ground), pin 8 of the oscillator goes to pin 7 of U6 (VCC). The oscillator output, pin 5, is connected to the hole on the right from JP9. Pin 1 of the oscillator goes to pin 2 of U6. Note that pin 1 in the oscillators can be either a "no connect' or "enable"... If using an oscillator with "enable", it might be needed to remove or otherwise not to connect pin 1...

It is possible to install an oscillator socket, if in the future one plans to experiment with the CPU clock.

The oscillator frequency should be the desired CPU/FPU frequency times two, e.g. 66 MHz for 33 MHz CPU clock.

**Comment by Marco-Both** [comment]
![IMG_8762](https://github.com/Marco-Both/M396F-Replika/assets/10757806/37f9f1b6-0c37-4ba6-b969-353e29f3e623)

I can confirm that a DIP-14 oscillator works. Unfortunately, I do not have a DIP-8. I will update the description.

**Comment by Marco-Both** [comment]
DIP-14 Confirmed and included in the description.
