### ISSUE TITLE
Pin 3 - +5V is not connected on ISA connector J7

### ISSUE THREAD

**Issue by skiselev** [Marco-Both/M396F-Replika#7]
Pin 3 - +5V is not connected on ISA connector J7.
Probably an omission then replicating the board.
Likely not a big deal, since ISA slot has two more +5V signals, but definitely something to fix in the next revision.

**Comment by Marco-Both** [comment]
Thank you for letting me know. Yes, it is true. A 5V trace is missing. I'll fix it this weekend and create new Gerber files.

**Comment by Marco-Both** [comment]
fixed
